### ISSUE TITLE
No 'Access-Control-Allow-Origin' header

### ISSUE THREAD

**Issue by hubdotcom** [chargebee/chargebee-checkout-samples#1]
Failed to load http://localhost:8000/api/generate_portal_session: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://0.0.0.0:9000' is therefore not allowed access. The response had HTTP status code 500.

**Comment by cb-dinesh** [comment]
You should enable CORS for the corresponding APIs on your backend server. 

Closing this issue. Please recreate a new one if there are any problems integrating Chargebee checkout.
