### ISSUE TITLE
Issue with 3DS Payment flow. 

### ISSUE THREAD

**Issue by uh-vish** [chargebee/chargebee-checkout-samples#110]
I am using [https://www.chargebee.com/checkout-portal-docs/3ds-helper-overview.html#_3-d-secure](url) for implementing 3DS Payment flow. 

1. Create Payment Intent on Server 
2. Tokenize Card 
3. 3DSHander with token + paymen_intent + additional fields 

Facing issue at Tokenization itself. 
It says Uncaught (in promise) Error: Gateway configuration for currency: undefined unavailable 

Or if added  publishedKey, for CbInstance, it says Api unauthorized. 

Please help. 
<img width="421" alt="Screenshot 2021-09-03 at 2 17 35 PM" src="https://user-images.githubusercontent.com/62738489/132003493-a6f5a0b3-4b40-481d-9530-52cdcc533810.png">
<img width="1432" alt="Screenshot 2021-09-03 at 5 45 20 PM" src="https://user-images.githubusercontent.com/62738489/132003629-007c4ff2-f8e7-4b6d-92ef-ed84b63c6b32.png">

**Comment by antti2000** [comment]
@uh-vish What was the underlying issue? Did you resolve it yourself? We are seeing something similar at the moment.
