### ISSUE TITLE
"Invalid card number" error testing the 3ds_full_checkout_examples

### ISSUE THREAD

**Issue by marinaserranomontes** [chargebee/chargebee-checkout-samples#14]
Hi,

I am testing your branch 3ds_full_checkout_examples.
I am able to generate the payment_intent using my server:
{"id":"169yCIRmbeeHZ66FKJTjMLMkONzNWZGA38Zcu6YxTa1DUcddPT","status":"inited","amount":3001,"gateway_account_id":"......","expires_at":1578138949,"created_at":1578137149,"modified_at":1578137149,"object":"payment_intent","currency_code":"USD","gateway":"chargebee"}

But, when I call to the "authorizeWith3ds" function, I am getting the following error "Invalid card number". I am using the testing cards here: https://www.chargebee.com/docs/chargebee-test-gateway.html#test-card-numbers_3ds-cards

Please, could you indicate to me what testing card number I need to use to check the authorizeWith3ds flow? 

Thanks,
Marina

**Comment by cb-dinesh** [comment]
Hi Marina,

Currently Chargebee's test gateway does not support 3DS. Please try with Stripe/Braintree's sandbox account and their corresponding 3DS test cards.

Thanks,
Dinesh

**Comment by marinaserranomontes** [comment]
Thanks Dinesh!!

I am testing your sample with the stripe connected account and the following cards https://stripe.com/docs/payments/3d-secure, but I am getting an "invalid token id" error. ......"active_payment_attempt":{"id":"AzqgpzRmcyMgT3Qn","status":"refused","error_text":"Invalid token id: tok_16CHQcRmcyMXN2s2; request-id: req_MYPi1mrDUZXYgz","created_at":1578156624,"modified_at":1578156624,"object":"payment_attempt"}}}...

**Comment by cb-dinesh** [comment]
Hey, Smart Routing rules needs to be set correctly. Please reach out to support@chargebee.com for further assistance.

Cheers,
Dinesh

**Comment by marinaserranomontes** [comment]
Thanks, @cb-dinesh. It worked!!!!
