### ISSUE TITLE
how to apply media query styling to input components

### ISSUE THREAD

**Issue by shierro** [chargebee/chargebee-checkout-samples#8]
hi! i've checked the documentation regarding the question, but i was unable to find any clue how to achieve this one. I basically want to apply some styles on the input element or `.CardInput` class, inside the iframe. 

My end goal is to make the font smaller on mobile, and bigger on desktop. Is this possible w/ the react implementation?

**Comment by cb-dinesh** [comment]
Hi Shierro,

It is possible to dynamically change the font-size on the react implementation. Although, media queries are not supported.

Refer to this [example](https://github.com/chargebee/chargebee-checkout-samples/blob/master/components/react-app/src/components/example1/Example1.js): Here you can modify the fontSize in the state, to achieve corresponding result.

Let me know if this solves your query.

Thanks. 
- Dinesh

**Comment by shierro** [comment]
hi Dinesh,

thanks for taking time to reply.

yup, that works for me. is it possible to support media queries in the near
future?

**Comment by cb-dinesh** [comment]
Support for media queries is already in our backlog. But there is no fixed ETA as of now. :)

**Comment by cb-dinesh** [comment]
Closing this issue. Please raise a new issue if there are any problems.
Thanks.
